### ISSUE TITLE
Bug of gem report

### ISSUE THREAD

**Issue by HolaFlight** [Noxde/Bloodborne-save-editor#7]
Thanks so much for making such a convenient tool, making it possible to have the most suitable gem for each weapon, I can finally be liberated from endless farming.

Bug report:
1, When customizing gems, it seems that there are some errors in adding or removing the “cursed” prefix, after modifying the negative entries, you can often see names such as “Cursed Cursed ...... Gems “.
2. When adding negative entries such as “Increases stamina consumption”, the program doesn't seem to add the “cursed” prefix to the gem correctly, and the icon isn't replaced with the icon of the cursed gem.
3. There seems to be a lot of duplicate entries and the order is very messy when selecting gem entries.

Feature Request:
Display gems in sorted in-game order, and preferably filter gems. (I have hundreds of gems. It's a pain to manually filter these gems with the mouse XD)

Question:
Do the items shown in the program include all items? Because I've made a cursory observation that the item counts don't show all the items in the savedata (e.g. the number of weapons)

**Comment by Noxde** [comment]
Glad that its been useful and thanks for the feedback!

As for the bugs:
1. That wasn't known, we'll look into it, should be easy to fix I think.
2. That's a known issue, I probably forgot to add a few curses so that should be an easy fix.
3. There are like 12496 options to choose from when selecting an effect, It's true that there are a lot of duplicates but they actually have different ids, we could probably just leave one of each but Im not sure if all of the duplicates have the same rating, that might not even be that important.

The gems were ordered at first but when you changed the first effect or the shape of a gem it would move in the inventory because of the ordering so i though it could be confusing, I could order them and maybe add a search or something like that.

And to answer your question, it should include all the items. We haven't looked into that yet but I know someone else on discord told me about it so we'll work on having it fixed for the next release.

Thanks for all the feedback!

**Comment by HolaFlight** [comment]
I found that some edited gems are not showing up in the game. However, when I export the save back to the editor, these gems that cannot be found in the game are still there. I’m concerned that this might cause some unknown irreversible effects on the save file, so I’ve temporarily reverted the save.

By the way, it would be great if it were possible to directly edit the gems embedded in weapons. Just a suggestion.

Thanks for the reply.

**Comment by mrbrisco** [comment]
@HolaFlight check your storage, it might be the same issue I had

**Comment by Noxde** [comment]
> I found that some edited gems are not showing up in the game. However, when I export the save back to the editor, these gems that cannot be found in the game are still there. I’m concerned that this might cause some unknown irreversible effects on the save file, so I’ve temporarily reverted the save.
> 
> By the way, it would be great if it were possible to directly edit the gems embedded in weapons. Just a suggestion.
> 
> Thanks for the reply.

Let me know if what mrbrisco said doesn't work and I'll look into that whenever I can and thanks for the suggestion, we want to add that at some point

**Comment by Noxde** [comment]
> I checked all the gems on the weapons, as well as the inventory and storage, and still missing those gems. However, now I'm not so sure if it's because I mixed up the save files, as this happened after a few edits (I'm using a Discord bot for encryption and decryption). I'll test more sometime later, and if this occurs again, I'll report more detail.

Pretty sure you should see them on your storage like mrbrisco said before, have you checked yet? the other issues have been solved on the latest release

**Comment by HolaFlight** [comment]
Yes, I checked all the gems at that time, including those on weapons and in the storage. In order to be easier to find, I changed the edited gem shape to droplet (droplet gems are the least in the game ands should be easy to found), but still cannot be found in game.

At the time I used several different bot conversions to convert the savedata and may have corrupted the data. After that I avoided modding too many gems at once and followed the instructions on the wiki exactly and haven't had this problem. I think this is difficult to reproduce and is also not that important.

Thank you for your efforts, I will download the latest version of the program to use and test.
